// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg4zEwcP4SiiUSHrHZPSnSlpHdDYu-iDs',
    appId: '1:751778719321:web:a037249288c1ebedfbb348',
    messagingSenderId: '751778719321',
    projectId: 'doc-doc-916b1',
    authDomain: 'doc-doc-916b1.firebaseapp.com',
    storageBucket: 'doc-doc-916b1.appspot.com',
    measurementId: 'G-EESY8D927C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYqhyi7RC17I9zgb95sQFF6qf__bN07M0',
    appId: '1:751778719321:android:45b762d7defa0407fbb348',
    messagingSenderId: '751778719321',
    projectId: 'doc-doc-916b1',
    storageBucket: 'doc-doc-916b1.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg4zEwcP4SiiUSHrHZPSnSlpHdDYu-iDs',
    appId: '1:751778719321:web:cceeac40e6522703fbb348',
    messagingSenderId: '751778719321',
    projectId: 'doc-doc-916b1',
    authDomain: 'doc-doc-916b1.firebaseapp.com',
    storageBucket: 'doc-doc-916b1.appspot.com',
    measurementId: 'G-JN8T85E95H',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAql-9edvoMCAIg3G8GiyrTz0sMVVbDwC0',
    appId: '1:751778719321:ios:a99080469954dc35fbb348',
    messagingSenderId: '751778719321',
    projectId: 'doc-doc-916b1',
    storageBucket: 'doc-doc-916b1.appspot.com',
    iosBundleId: 'com.docdoc.app.docdocApp',
  );

}